language: php
php:
  - "5.3"
branches:
only:
  - master

env:
  - DB=mysql
  - DB=mysqli
  - DB=pdo/mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS mytest;" -uroot; fi
  
script: phpunit --coverage-text --configuration $DB.phpunit.xml

